name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DISPLAY: ':99'
      
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with ruff
        run: |
          # default set of ruff rules with GitHub Annotations
          poetry run ruff --format=github --target-version=py311 .
      - name: Test with pytest
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          poetry run pytest
